export const TEXTS = {
    EN: {
        PLAY: "PLAY",
        SETTINGS: "SETTINGS",
        SKINS: "SKINS",
        THEMES: "THEMES",
        CHALLENGE: "CHALLENGE",
        GAME_OVER: "GAME OVER",
        SCORE: "Score",
        BEST: "Best",
        RETRY: "RETRY",
        MENU: "MENU",
        SHARE: "SHARE",
        PAUSED: "PAUSED",
        RESUME: "RESUME",
        RESTART: "RESTART",
        MAIN_MENU: "MAIN MENU",
        SOUND: "Sound",
        MUSIC: "Music",
        LANGUAGE: "Language",
        PRIVACY: "Privacy Policy",
        CLOSE: "CLOSE",
        UNLOCK_WITH_AD: "Watch Ad to Unlock?",
        AD_FAILED: "Ad failed or cancelled.",
        SKIN_UNLOCKED: "Unlocked!",
        LOCKED: "Locked",
        DAILY_CHALLENGE: "DAILY CHALLENGE",
        START: "START",
        REWARD: "REWARD",
        NO_CHALLENGE: "No Challenge for Today :(",
        COMPLETED_MSG: "Challenge Completed!",
        TUTORIAL_TAP: "Tap to Drop",
        BACK: "Back"
    },
    TR: {
        PLAY: "OYNA",
        SETTINGS: "AYARLAR",
        SKINS: "KOSTÜM",
        THEMES: "TEMA",
        CHALLENGE: "GÖREV",
        GAME_OVER: "OYUN BİTTİ",
        SCORE: "Skor",
        BEST: "Rekor",
        RETRY: "TEKRAR",
        MENU: "MENÜ",
        SHARE: "PAYLAŞ",
        PAUSED: "DURAKLATILDI",
        RESUME: "DEVAM ET",
        RESTART: "YENİDEN BAŞLA",
        MAIN_MENU: "ANA MENÜ",
        SOUND: "Ses",
        MUSIC: "Müzik",
        LANGUAGE: "Dil / Language",
        PRIVACY: "Gizlilik Politikası",
        CLOSE: "KAPAT",
        UNLOCK_WITH_AD: "Açmak için reklam izle?",
        AD_FAILED: "Reklam yüklenemedi.",
        SKIN_UNLOCKED: "Açıldı!",
        LOCKED: "Kilitli",
        DAILY_CHALLENGE: "GÜNLÜK GÖREV",
        START: "BAŞLA",
        REWARD: "ÖDÜL",
        NO_CHALLENGE: "Bugün için görev yok :(",
        COMPLETED_MSG: "Görev Tamamlandı!",
        TUTORIAL_TAP: "Bırakmak için Dokun",
        BACK: "Geri"
    }
};
