export const TEXTS = {
    EN: {
        PLAY: "PLAY",
        SETTINGS: "SETTINGS",
        SKINS: "SKINS",
        THEMES: "THEMES",
        CHALLENGE: "CHALLENGE",
        GAME_OVER: "GAME OVER",
        SCORE: "Score",
        BEST: "Best",
        RETRY: "RETRY",
        MENU: "MENU",
        SHARE: "SHARE",
        PAUSED: "PAUSED",
        RESUME: "RESUME",
        RESTART: "RESTART",
        MAIN_MENU: "MAIN MENU",
        SOUND: "Sound",
        MUSIC: "Music",
        LANGUAGE: "Language",
        PRIVACY: "Privacy Policy",
        CLOSE: "CLOSE",
        UNLOCK_WITH_AD: "Watch Ad to Unlock?",
        AD_FAILED: "Ad failed or cancelled.",
        SKIN_UNLOCKED: "Unlocked!",
        LOCKED: "Locked",
        DAILY_CHALLENGE: "DAILY CHALLENGE",
        START: "START",
        REWARD: "REWARD",
        NO_CHALLENGE: "No Challenge for Today :(",
        COMPLETED_MSG: "Challenge Completed!",
        TUTORIAL_TAP: "Tap to Drop",
        BACK: "Back",

        // New Additions
        OWNED: "Owned",
        ACTIVE: "Active",
        BUY_FOR: "Buy for", // e.g., "Buy for 50 Coins?"
        TRIAL_AD: "Trial (Ad)",
        SCORE_REQ: "Score >",
        DAY_REQ: "Day:",
        NOT_ENOUGH_COINS: "Not enough coins!",
        BOUGHT: "Bought!",
        WATCH_AD_CONFIRM: "Watch an Ad to unlock?",
        TRIAL_CONFIRM: "Watch Ad to try this theme for this session?",
        SESSION_APPLIED: "Theme applied for this session!",
        ERROR_NO_COIN_SYS: "Error: No Coin System",
        UNLOCK_VIA: "Unlock via:",
        VIBRATION: "Vibration",
        WATCH_AD_2X: "Watch 2x Win",
        YOU_WON_COINS: "You won"
    },
    TR: {
        PLAY: "OYNA",
        SETTINGS: "AYARLAR",
        SKINS: "KOSTÜM",
        THEMES: "TEMA",
        CHALLENGE: "GÖREV",
        GAME_OVER: "OYUN BİTTİ",
        SCORE: "Skor",
        BEST: "Rekor",
        RETRY: "TEKRAR",
        MENU: "MENÜ",
        SHARE: "PAYLAŞ",
        PAUSED: "DURAKLATILDI",
        RESUME: "DEVAM ET",
        RESTART: "YENİDEN BAŞLA",
        MAIN_MENU: "ANA MENÜ",
        SOUND: "Ses",
        MUSIC: "Müzik",
        LANGUAGE: "Dil / Language",
        PRIVACY: "Gizlilik Politikası",
        CLOSE: "KAPAT",
        UNLOCK_WITH_AD: "Açmak için reklam izle?",
        AD_FAILED: "Reklam yüklenemedi.",
        SKIN_UNLOCKED: "Açıldı!",
        LOCKED: "Kilitli",
        DAILY_CHALLENGE: "GÜNLÜK GÖREV",
        START: "BAŞLA",
        REWARD: "ÖDÜL",
        NO_CHALLENGE: "Bugün için görev yok :(",
        COMPLETED_MSG: "Görev Tamamlandı!",
        TUTORIAL_TAP: "Bırakmak için Dokun",
        BACK: "Geri",

        // New Additions
        OWNED: "Sahip",
        ACTIVE: "Aktif",
        BUY_FOR: "Satın al:", // e.g. "Satın al: 50 Coin?"
        TRIAL_AD: "Deneme (Reklam)",
        SCORE_REQ: "Skor >",
        DAY_REQ: "Gün:",
        NOT_ENOUGH_COINS: "Yetersiz Bakiye!",
        BOUGHT: "Satın Alındı!",
        WATCH_AD_CONFIRM: "Kilidi açmak için reklam izle?",
        TRIAL_CONFIRM: "Bu oturumda denemek için reklam izle?",
        SESSION_APPLIED: "Tema bu oturum için uygulandı!",
        ERROR_NO_COIN_SYS: "Hata: Coin Sistemi Yok",
        UNLOCK_VIA: "Kilit Yöntemi:",
        VIBRATION: "Titreşim",
        WATCH_AD_2X: "İzle 2x Kazan",
        YOU_WON_COINS: "Kazandın"
    }
};
